### ISSUE TITLE
Generate Java byte code

### ISSUE THREAD

**Issue by cycl0n3** [CondorLang/Condor#5]
Maybe we can generate java bytecode with your language.

**Comment by chaseWillden** [comment]
Just to clarify, what you are saying, take the syntax of my code and translate it into the Java bytecode so that my language can run with the Java JVM? That is an interesting idea? Have you done any research on how to do that or implement it? Great idea though.

**Comment by cycl0n3** [comment]
Writing bytecode directly is difficult process, so what can be done is producing intermediate `Jasmine` files which then can be compiled to java bytecode. I found this link [http://www.ceng.metu.edu.tr/courses/ceng444/link/f3jasmintutorial.html] to be useful.
The homepage is: [http://jasmin.sourceforge.net/guide.html]
