### ISSUE TITLE
There is already a Cobra language

### ISSUE THREAD

**Issue by charles-esterbrook** [CondorLang/Condor#6]
First, congratulations are creating a new language!

Second, the following language has been out for several years and has been called Cobra the entire time: http://cobra-language.com/

It has a wikipedia entry and is referenced on the Python wikipedia page:
https://en.wikipedia.org/wiki/Python_(programming_language)#Languages_influenced_by_Python

It's also been covered by InfoWorld and other places.

I think choosing the same name is inappropriate and potentially confusing. I recommend picking a name that doesn't duplicate existing languages. Here is a list:
http://regulargeek.com/2012/12/08/the-big-list-of-256-programming-languages/

Or you can search google for "foo programming language" for any candidate name "foo"

Best regards,

Charles Esterbrook
Creator of [Cobra](http://cobra-language.com/)

**Comment by chaseWillden** [comment]
Is Cobra an open source language?

**Comment by charles-esterbrook** [comment]
Yes. MIT license.

**Comment by chaseWillden** [comment]
Ok I'll see what I can do.
