### ISSUE TITLE
Building the memory tests

### ISSUE THREAD

**Issue by Berkmann18** [CondorLang/Condor#9]
## Expected Behavior

Memory test results.
## Current Behavior

``` bash
valgrind --tool=memcheck --leak-check=full --track-origins=yes --dsymutil=yes ./build/linux/condor > log.txt 2>&1
Makefile:112: recipe for target 'mem' failed
make: *** [mem] Error 127
```
## Steps to Reproduce

``` bash
git clone https://github.com/CondorLang/Condor/
cd Condor
make all
make || make mt
make shell
sudo apt-get install valgrind
make mem #note: runing sudo apt-get update before gives the same result when running this line
```
## Context (Environment)

I was trying to set up the CondorLang dev environment (to use/test/improve it) on Linux Ubuntu 16.04 LTS (64-bit) and I run into this problem.

**Comment by chaseWillden** [comment]
@Berkmann18 Are you sure Valgrind actually installed on your Linux machine? When I run it on my newly created Ubuntu 16.04 LTS, it works for me. Try just typing valgrind into the terminal.

**Comment by Berkmann18** [comment]
@chaseWillden Yes `valgrind --version` returns `valgrind-3.11.0`.
I reran `make mem` after restarting my Ubuntu OS (I'm dual booting on that and Win10.3) and it now returns

``` bash
valgrind --tool=memcheck --leak-check=full --track-origins=yes --dsymutil=yes ./build/linux/condor > log.txt 2>&1
```

Is that what you got (and perhaps what should be outputed on the screen) ?

**Comment by chaseWillden** [comment]
Removed from Makefile. Switched to cmake to generate makefile to hopefully prevent bugs.
